CLUSTAL multiple sequence alignment by MUSCLE (3.8)


black               ----------------------------------------------CDNADKK------V
XP_025865652.1      MSSEAETQQPP----TAPALSAADTKPGTTGSGAGSGGPGGLTSAAPAGGDKK------V
XP_011376282.1      -------------------------------------MAKGLEDWTRNVKDERSWVFFPL
XP_025782261.1      --------------------------------------------------DRK------V
NP_001087255.1      ----------------------------------------GLTSAAPAGGDKK------V
XP_004871881.1      MSSEAETQQPPAAPPAAPALSAADTKPGTTGSGAGSGGPGGLTSAAPAGGDKK------V
NP_004550.2         MSSEAETQQPPAAPPAAPALSAADTKPGTTGSGAGSGGPGGLTSAAPAGGDKK------V
                                                                      * .      :

black               IATKVLGTVKWFNVRNGYGFINRNDTKEDVFVHQTAIKKNNPRKYLRSVGDGETVEFDVV
XP_025865652.1      IATKVLGTVKWFNVRNGYGFINRNDTKEDVFVHQTAIKKNNPRKYLRSVGDGDTVEFDVV
XP_011376282.1      SATKVLGTVKWFNVRNGYGFINRNDTKEDVFVHQTAIKKNNPRKYLRSVGDGETVEFDVV
XP_025782261.1      ISTKVLGTVKWFNVRNGYGFINRNDTKEDVFVHQTAIKKNNPRKYLRSVGDGETVEFDVV
NP_001087255.1      IATKVLGTVKWFNVRNGYGFINRNDTKEDVFVHQTAIKKNNPRKFLRSVGDGETVEFDVV
XP_004871881.1      IATKVLGTVKWFNVRNGYGFINRNDTKEDVFVHQTAIKKNNPRKYLRSVGDGETVEFDVV
NP_004550.2         IATKVLGTVKWFNVRNGYGFINRNDTKEDVFVHQTAIKKNNPRKYLRSVGDGETVEFDVV
                     :******************************************:*******:*******

black               EGEKGAEAANVTGPGGVPVQGSKYAAD---------------------------------
XP_025865652.1      EGEKGAEAANVTGPGGVPVQGSKYAADRNHYRRYPRRRGPPRNYQQNYQNSESGEKNQGS
XP_011376282.1      EGEKGAEAANVTGPGGVPVQGSKYAADRNHYRRYPRRRGPPRNYQQNYQNSESGEKNEGS
XP_025782261.1      EGEKGAEAANVTGPGGVPVQGSKYAADRNHYRRYPRRRGPPRNYQQNYQNSESGEKNEGS
NP_001087255.1      EGEKGAEAANVTGPGGVPVQGSKYAADRNHYRRYPRRRGPPRNYQQNYQNSESGEKNEGS
XP_004871881.1      EGEKGAEAANVTGPGGVPVQGSKYAADRNHYRRYPRRRGPPRNYQQNYQNSESGEKNEGS
NP_004550.2         EGEKGAEAANVTGPGGVPVQGSKYAADRNHYRRYPRRRGPPRNYQQNYQNSESGEKNEGS
                    ***************************                                 

black               ------------------------------------------------------------
XP_025865652.1      ESAPEGQAQQRRPYRRRRFPPYYMRRPYGPRPQYSNPPVQGEVMEGADNQGAGEQGRPVR
XP_011376282.1      ESAPEGQAQQRRPYRRRRFPPYYMRRPYGRRPQYSNPPVQGEVMEGADNQGAGEQGRPVR
XP_025782261.1      ESAPEGQAQQRRPYRRRRFPPYYMRRPYGRRPQYSNPPVQGEVMEGADNQGAGEQGRPVR
NP_001087255.1      ESAPEGQAQQRRPYRRRRFPPYYMRRPYGRRPQYSNPPVQGEVMEGADNQGAGEQGRPVR
XP_004871881.1      ESAPEGQAQQRRPYRRRRFPPYYMRRPYGRRPQYSNPPVQGEVMEGADNQGAGEQGRQVR
NP_004550.2         ESAPEGQAQQRRPYRRRRFPPYYMRRPYGRRPQYSNPPVQGEVMEGADNQGAGEQGRPVR
                                                                                

black               ------------------------------------------------------------
XP_025865652.1      QNMYRGYRPRFRRGPPHQRQPREDGNEEDKENQGDETQGQQPPQRRYRRNFNDRRRRPEN
XP_011376282.1      QNMYRGYRPRFRRGPPRQRQPREDGNEEDKENQGDETQGQQPPQRRYRRNFNYRRRRPEN
XP_025782261.1      QNMYRGYRPRFRRGPPRQRQPREDGNEEDKENQGDETQGQQPPQRRYRRNFNYRRRRPEN
NP_001087255.1      QNLYRGYRPRFRRGPPRQRQPREDGNEEDKENQGDETQGQQPPQRRYRRNFNYRRRRPEN
XP_004871881.1      QNMYRGYRPRFRRGPPRQRQPREDGNEEDKENQGDETQGQQPPQRRYRRNFNYRRRRPEN
NP_004550.2         QNMYRGYRPRFRRGPPRQRQPREDGNEEDKENQGDETQGQQPPQRRYRRNFNYRRRRPEN
                                                                                

black               ------------------------------
XP_025865652.1      PKPQDGKETKAADPPAENSSAPEAEQGGAE
XP_011376282.1      PKPQDGKETKAADPPAENSSAPEAEQGGAE
XP_025782261.1      PKPQDGKETKAADPPAENSSAPEAEQGGAE
NP_001087255.1      PKPQDGKETKAADPPAENSSAPEAEQGGAE
XP_004871881.1      PKPQDGKETKAADPPAENSSAPEAEQGGAE
NP_004550.2         PKPQDGKETKAADPPAENSSAPEAEQGGAE
                                                  
