---
title: 'Class 7: R functions and packages'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## more on function writing 
First we will use the same function from the other day 

```{r}
source("http://tinyurl.com/rescale-R")

rescale <- function(x, na.rm=TRUE, plot=FALSE, ...) {
  if( !is.numeric(x) ) {
 stop("Input x should be numeric", call.=FALSE)
 }
  rng <-range(x, na.rm=na.rm)
  
  answer <- (x - rng[1]) / (rng[2] - rng[1])
  if(plot) {
    plot(answer, ...)
  }
  return(answer)
}

rescale( c(1:10) )

```

## writing a function
first make sure you can solve the right stuff 


```{r}
x <- c( 1, 2, NA, 3, NA)
y <- c(NA, 3, NA, 3, 4)


if (sum(is.na(x)) >= 1 & sum(is.na(y)) >= 1) {
  print("I work!")
}



```

```{r}


both_na <- function(x,y) {
  if (sum(is.na(x)) >= 1 & sum(is.na(y)) >= 1) {
  print("I work!")
}
}





```

```{r}
both_na3 <- function(x, y) {
 if(length(x) != length(y)) {
 stop("Input x and y should be vectors of the same length")
 }

 na.in.both <- ( is.na(x) & is.na(y) )
 na.number <- sum(na.in.both)
 na.which <- which(na.in.both)
 message(
  
 )

 return( list(number=na.number, which=na.which) )
}


both_na3(x,y)
```
```{r}
student1 <- c(100, 100, 100, 100, 100,100, 100, 90)
student2 <- c(100, NA, 90, 90,90, 90, 97, 80)

calculate_grade <- function(student){
  if(sum(is.na(student)) >= 1) {
    student <- replace(student, is.na(student), 0)
  }
  this_min = min(student)
  average = (sum(student) - this_min) / (length(student) - 1)
  print("The average for the student is:")
  print(average)
}

calculate_grade(student2)

```
```{r}
df <- read.csv('student_homework.csv', row.names = 1)
df

calculate_grade(df[1,])

answer <- apply(df, 1 ,calculate_grade)

```
```{r}
sort(answer, decreasing = TRUE)
```
```{r}
df1 <- data.frame(IDs=c("gene1", "gene2", "gene3"),
 exp=c(2,1,1),
 stringsAsFactors=FALSE)
df2 <- data.frame(IDs=c("gene2", "gene4", "gene3", "gene5"),
 exp=c(-2, NA, 1, 2),
 stringsAsFactors=FALSE)



x <- df1$IDs
y <- df2$IDs

intersect(x, y)
gene_intersect <- function(x, y) {
  cbind( x[ x %in% y ], y[ y %in% x ] )
}


gene_intersect(x,y)

  
install.packages("BiocManager")
BiocManager::install()

install.packages("ggplot2")
library("ggplot2")
f <- ggplot(df["student-18"])

df
```

```{r}
library(tidyverse)
housing <- read_csv("dataSets/landdata-states.csv")
plot(Home.Value ~ Date,
     col = factor(State),
     data = filter(housing, State %in% c("MA", "TX")))
legend("topleft",
       legend = c("MA", "TX"),
       col = c("black", "red"),
       pch = 1)


```

```{r}
ggplot(filter(housing, State %in% c("MA", "TX")),
       aes(x=Date,
           y=Home.Value,
           color=State))+
  geom_point()

```


```{r}
